const fs = require("fs");
const path = require("path");

const generateReport = (casePath, data) => {
  try {
    const reportContent = `
==============================
      THREAT ANALYSIS REPORT
==============================

Case Name: ${data.caseName}

--------------------------------
Extracted IOCs:
${JSON.stringify(data.extractedIOCs, null, 2)}

--------------------------------
Threat Intelligence Results:
${JSON.stringify(data.threatResults, null, 2)}

--------------------------------
Analytics Report:
${JSON.stringify(data.analyticsReport, null, 2)}

================================
Generated By: Threat Intelligence System
================================
`;

    const reportPath = path.join(casePath, "final_report.txt");

    fs.writeFileSync(reportPath, reportContent);

    return reportPath;

  } catch (error) {
    throw new Error("Report generation failed: " + error.message);
  }
};

module.exports = {
  generateReport
};